name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Set up Python
      run: uv python install 3.9  # Adjust Python version if needed

    - name: Install dependencies
      run: uv sync

    - name: Make eval.sh and run.sh executable
      run: |
        chmod +x eval.sh
        chmod +x run.sh

    - name: Run eval.sh
      run: ./eval.sh