[project]
name = "top-coder-challenge"
version = "1.0.0"
dependencies = [
    "numpy>=1.21.0",
    "scipy>=1.7.0",
    "scikit-learn>=1.0.0",
]

[tool.uv]
python-version = "3.9"  # Adjust if challenge specifies a different version